// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260108221746_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);


            modelBuilder.Entity("Repositories.Models.RaceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");


                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Drivers")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("RaceFormat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Results")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrackId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrackId");

                    b.ToTable("Races");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Contact = "Manuel Thiry (MATH)",
                            Date = new DateTime(2026, 1, 15, 20, 0, 0, 585, DateTimeKind.Unspecified),
                            Drivers = "Manuel THIRY, Maxime BECKERS, Simon MAUDOUX, Pierre MIGNOLET, Thibaut MARECHAL, Aubry HUYGHEBAERT, Jeremy MAHIAT, Pierre JACOBS, Quentin BOILEAU, Loic PETERS",
                            Period = "January",
                            Price = 56,
                            RaceFormat = "Q: 6min, R: 30min",
                            Results = "",
                            TrackId = 2
                        },
                        new
                        {
                            Id = 3,
                            Contact = "",
                            Drivers = "",
                            Period = "March",
                            Price = 0,
                            RaceFormat = "",
                            Results = "",
                            TrackId = 3
                        },
                        new
                        {
                            Id = 4,
                            Contact = "",
                            Drivers = "",
                            Period = "May",
                            Price = 0,
                            RaceFormat = "",
                            Results = "",
                            TrackId = 4
                        },
                        new
                        {
                            Id = 5,
                            Contact = "",
                            Drivers = "",
                            Period = "July",
                            Price = 0,
                            RaceFormat = "",
                            Results = "",
                            TrackId = 5
                        },
                        new
                        {
                            Id = 6,
                            Contact = "",
                            Drivers = "",
                            Period = "September",
                            Price = 0,
                            RaceFormat = "",
                            Results = "",
                            TrackId = 6
                        },
                        new
                        {
                            Id = 7,
                            Contact = "",
                            Drivers = "",
                            Period = "November",
                            Price = 0,
                            RaceFormat = "",
                            Results = "",
                            TrackId = 7
                        });
                });

            modelBuilder.Entity("Repositories.Models.TrackModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");


                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Length")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Image = "https://s3.eu-west-3.amazonaws.com/sport-finder.image/images/cache/full_hd/center/karting-eupen.jpeg",
                            Length = "1.1 km",
                            Location = "Industriestraße 37, 4700 Eupen",
                            Name = "Experience Factory Eupen"
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://www.liegekarting.com/upload/liege-karting-5b3b97-large.jpg",
                            Length = "530 m",
                            Location = "Rue Eugène Vandenhoff 88, 4030 Liège",
                            Name = "Liege Karting"
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://www.francorchamps-karting.be/images/site/2024121814_1734530354e2.jpg",
                            Length = "1.0 km",
                            Location = "Rte de l' Eau Rouge 51, 4970 Stavelot",
                            Name = "RACB Karting Spa-Francorchamps"
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://www.lavenir.net/resizer/v2/AVCT2F553ZEFJEXQ3SEYOQRKN4.jpg?auth=0b9be8d04b9e73a078e70838860f29bc40f18b1287b72d0af458d09e9fa95987&width=1620&height=1085&quality=85&focal=512%2C343",
                            Length = "1.3 km",
                            Location = "Rue du Karting 13, 5660 Couvin",
                            Name = "Karting des Fagnes"
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://i.pinimg.com/564x/90/7c/2f/907c2f8ecc87c1688948ed0dee503761.jpg",
                            Length = "600 m",
                            Location = "Av. Reine Astrid 97/A, 4831 Limbourg",
                            Name = "Hurricane Dolhain Karting"
                        },
                        new
                        {
                            Id = 7,
                            Image = "",
                            Length = "",
                            Location = "",
                            Name = ""
                        });
                });

            modelBuilder.Entity("Repositories.Models.RaceModel", b =>
                {
                    b.HasOne("Repositories.Models.TrackModel", "Track")
                        .WithMany()
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Track");
                });
#pragma warning restore 612, 618
        }
    }
}
